"""SEC03 restore tests on ephemeral localhost PostgreSQL; never production IO."""
from pathlib import Path
import json, os, re, subprocess
ROOT = Path(__file__).resolve().parents[1]
if os.environ.get('SEC03_ISOLATED') != '1':
    raise SystemExit('Run only in the disposable localhost SEC03 CI database')
env = {k:v for k,v in os.environ.items() if not k.startswith('PG')}
env['PGPASSWORD'] = 'synthetic-sec03'
args = ['psql','-X','-q','-v','ON_ERROR_STOP=1','-At','-h','127.0.0.1','-p','5432','-U','postgres','-d','sec03_test']
source = (ROOT/'supabase/migrations/20260928110947_security_fix3_backup_legacy_tables.sql').read_text()
helpers = '\n'.join(re.findall(r'CREATE FUNCTION pg_temp\.sec03_(?:capture|fingerprint)\(\)[\s\S]*?END \$f\$;', source))
assert helpers.count('CREATE FUNCTION') == 2
restore = (ROOT/'maintenance/sec03_restore_rehearsal.sql').read_text()
assert not re.search(r'\bDROP\s+(?:TABLE|SCHEMA)\b', restore, re.I)
assert 'NULL::%s,$1' in restore
setup = r"""
BEGIN;
SET LOCAL search_path=pg_catalog;
CREATE SCHEMA purchasing_private;
CREATE SCHEMA auth;
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN;
CREATE TABLE auth.users(id uuid PRIMARY KEY);
INSERT INTO auth.users VALUES ('11111111-1111-4111-8111-111111111111');
CREATE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path='public','pg_temp' AS $$ BEGIN new.updated_at=now(); RETURN new; END; $$;
CREATE TABLE public.products_master(product_code text NOT NULL,product_name text NOT NULL,purchase_unit text NOT NULL,option_unit text,factor numeric(18,6) DEFAULT 1 NOT NULL,reorder_point numeric(18,6),profitability_class text,supplier text,updated_at timestamptz DEFAULT now() NOT NULL,PRIMARY KEY(product_code),CHECK(factor>0),CHECK(reorder_point IS NULL OR reorder_point>=0));
CREATE TABLE public.inventory_uploads(id uuid DEFAULT gen_random_uuid() PRIMARY KEY,uploaded_at timestamptz DEFAULT now() NOT NULL,file_name text NOT NULL,uploaded_by uuid REFERENCES auth.users(id),total_rows integer DEFAULT 0 NOT NULL CHECK(total_rows>=0),matched_rows integer DEFAULT 0 NOT NULL CHECK(matched_rows>=0),unmatched_rows integer DEFAULT 0 NOT NULL CHECK(unmatched_rows>=0),status text DEFAULT 'processing' NOT NULL CHECK(status IN ('processing','completed','error')),notes text);
CREATE TABLE public.inventory_lines(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,upload_id uuid NOT NULL REFERENCES public.inventory_uploads(id) ON DELETE CASCADE,product_code text,raw_product_name text,raw_quantity numeric(18,6) NOT NULL,raw_unit text,normalized_quantity numeric(18,6),purchase_unit text,reorder_point numeric(18,6),profitability_class text,supplier text,stock_ratio numeric(18,6),min_order_qty numeric(18,6),max_order_qty numeric(18,6),needs_review boolean DEFAULT false NOT NULL,review_reason text,created_at timestamptz DEFAULT now() NOT NULL);
CREATE INDEX idx_products_master_supplier ON public.products_master(supplier);
CREATE INDEX idx_products_master_profitability ON public.products_master(profitability_class);
CREATE INDEX idx_inventory_lines_upload_id ON public.inventory_lines(upload_id);
CREATE INDEX idx_inventory_lines_product_code ON public.inventory_lines(product_code);
CREATE TRIGGER trg_products_master_updated_at BEFORE UPDATE ON public.products_master FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
ALTER TABLE public.products_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_uploads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_lines ENABLE ROW LEVEL SECURITY;
CREATE POLICY products_master_authenticated_all ON public.products_master FOR ALL TO authenticated USING(true) WITH CHECK(true);
CREATE POLICY inventory_uploads_authenticated_all ON public.inventory_uploads FOR ALL TO authenticated USING(true) WITH CHECK(true);
CREATE POLICY inventory_lines_authenticated_all ON public.inventory_lines FOR ALL TO authenticated USING(true) WITH CHECK(true);
GRANT ALL ON public.products_master,public.inventory_uploads,public.inventory_lines TO anon,authenticated,service_role;
COMMENT ON TABLE public.products_master IS 'Synthetic legacy baseline';
COMMENT ON COLUMN public.products_master.product_name IS 'Quotes '' and unicode are data';
INSERT INTO public.products_master(product_code,product_name,purchase_unit,option_unit,factor,reorder_point,profitability_class,supplier)
 SELECT 'QA'||lpad(i::text,4,'0'),'Synthetic product '||i||' O''Brien','Box',CASE WHEN i%2=0 THEN 'Piece' END,CASE WHEN i%2=0 THEN 12 ELSE 1 END,CASE WHEN i%3=0 THEN NULL ELSE 100 END,CASE WHEN i%4=0 THEN NULL ELSE 'High' END,CASE WHEN i%5=0 THEN NULL ELSE 'QA Supplier' END FROM generate_series(1,1576) i;
INSERT INTO public.inventory_uploads(id,file_name,uploaded_by,total_rows,matched_rows,unmatched_rows,status,notes) VALUES('22222222-2222-4222-8222-222222222222','SYNTHETIC.csv','11111111-1111-4111-8111-111111111111',1309,1300,9,'completed','Not customer data');
INSERT INTO public.inventory_lines(upload_id,product_code,raw_product_name,raw_quantity,raw_unit,normalized_quantity,purchase_unit,reorder_point,profitability_class,supplier,stock_ratio,min_order_qty,max_order_qty,needs_review,review_reason)
 SELECT '22222222-2222-4222-8222-222222222222'::uuid,'QA'||lpad(i::text,4,'0'),'Synthetic '||i,CASE WHEN i%7=0 THEN -1.250001 ELSE i+0.123456 END,'Piece',i/12.0,'Box',100,'High',CASE WHEN i%5=0 THEN NULL ELSE 'QA Supplier' END,i,0,100,i%7=0,CASE WHEN i%7=0 THEN 'Negative stock' END FROM generate_series(1,1309) i;
-- Nonlegacy canaries: these verify object/data isolation, not full V5 emulation.
CREATE TABLE public.products_master_v5(code text PRIMARY KEY,price numeric);
CREATE TABLE public.inventory_uploads_v5(id integer PRIMARY KEY);
CREATE TABLE public.inventory_lines_v5(id integer PRIMARY KEY,quantity numeric);
INSERT INTO public.products_master_v5 VALUES('CURRENT',20);
INSERT INTO public.inventory_uploads_v5 VALUES(5);
INSERT INTO public.inventory_lines_v5 VALUES(5,120);
CREATE TABLE purchasing_private.retired_legacy_snapshot_v1(snapshot_key text PRIMARY KEY,captured_at timestamptz DEFAULT now(),payload jsonb,payload_md5 text,verification jsonb);
"""
seed = """
INSERT INTO purchasing_private.retired_legacy_snapshot_v1(snapshot_key,payload,payload_md5,verification)
 SELECT 'sec03_legacy_retirement',b,md5(b::text),'{}'::jsonb FROM (SELECT pg_temp.sec03_capture() b) q;
CREATE TEMP TABLE qa_before AS SELECT pg_temp.sec03_fingerprint() AS other_state,pg_temp.sec03_capture() AS legacy_state;
"""
verify = """
DO $$ DECLARE x jsonb; BEGIN
 IF (SELECT other_state FROM qa_before) IS DISTINCT FROM pg_temp.sec03_fingerprint() OR (SELECT legacy_state FROM qa_before) IS DISTINCT FROM pg_temp.sec03_capture() THEN RAISE EXCEPTION 'Business source changed'; END IF;
 SELECT result INTO x FROM pg_temp.sec03_restore_result;
 IF x->'tables'->'products_master'->>'restored_rows'<>'1576' OR x->'tables'->'inventory_uploads'->>'restored_rows'<>'1' OR x->'tables'->'inventory_lines'->>'restored_rows'<>'1309' THEN RAISE EXCEPTION 'Count mismatch'; END IF;
 IF (SELECT count(*) FROM pg_indexes WHERE schemaname LIKE 'pg_temp_%' AND tablename LIKE 'sec03_restore_%')<>8 THEN RAISE EXCEPTION 'Restored indexes missing'; END IF;
 IF (SELECT count(*) FROM pg_trigger WHERE tgrelid='pg_temp.sec03_restore_products_master'::regclass AND NOT tgisinternal)<>1 THEN RAISE EXCEPTION 'Restored trigger missing'; END IF;
 UPDATE pg_temp.sec03_restore_products_master SET updated_at='2000-01-01' WHERE product_code='QA0001';
 IF (SELECT updated_at FROM pg_temp.sec03_restore_products_master WHERE product_code='QA0001')<>now() THEN RAISE EXCEPTION 'Restored trigger not working'; END IF;
 IF nextval(pg_get_serial_sequence('pg_temp.sec03_restore_inventory_lines','id'))<>1310 THEN RAISE EXCEPTION 'Restored identity wrong'; END IF;
 IF (SELECT last_value FROM public.inventory_lines_id_seq)<>1309 THEN RAISE EXCEPTION 'Original sequence changed'; END IF;
 IF (SELECT other_state FROM qa_before) IS DISTINCT FROM pg_temp.sec03_fingerprint() OR (SELECT legacy_state FROM qa_before) IS DISTINCT FROM pg_temp.sec03_capture() THEN RAISE EXCEPTION 'Rehearsal side effects'; END IF;
END; $$;
"""

def run(label, mutation='', expected=None, suffix=verify):
    p=subprocess.run(args,input=setup+helpers+seed+mutation+restore+suffix+'\nROLLBACK;',text=True,capture_output=True,env=env,timeout=90)
    if expected is None:
        if p.returncode: raise RuntimeError(label+'\n'+p.stdout+'\n'+p.stderr)
    elif p.returncode==0 or expected not in p.stderr:
        raise RuntimeError('Wrong failure: '+label+'\n'+p.stdout+'\n'+p.stderr)
    print('PASS',label)

run('full restore 1576/1/1309, exact hashes, FK, indexes, trigger, identity, hardened access and source isolation')
run('checksum mismatch rejected',"UPDATE purchasing_private.retired_legacy_snapshot_v1 SET payload_md5='bad';",'missing, damaged or unsupported')
run('shared trigger drift rejected',"CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path='public','pg_temp' AS $$ BEGIN RETURN new; END; $$;",'shared trigger source changed')

def alter_data(table,key,value):
    return "UPDATE purchasing_private.retired_legacy_snapshot_v1 SET payload=jsonb_set(payload,'{tables,"+table+",data,0,"+key+"}', '"+json.dumps(value)+"'::jsonb);\n"+"UPDATE purchasing_private.retired_legacy_snapshot_v1 SET payload=jsonb_set(payload,'{tables,"+table+",data_md5}',to_jsonb(md5((payload->'tables'->'"+table+"'->'data')::text)));\nUPDATE purchasing_private.retired_legacy_snapshot_v1 SET payload_md5=md5(payload::text);\n"
run('factor CHECK is enforced',alter_data('products_master','factor',-1),'violates check constraint')
run('NOT NULL is enforced',alter_data('products_master','product_name',None),'violates not-null constraint')
run('inventory parent FK is enforced',alter_data('inventory_lines','upload_id','33333333-3333-4333-8333-333333333333'),'violates foreign key constraint')
run('missing auth parent rejected without writing auth',alter_data('inventory_uploads','uploaded_by','33333333-3333-4333-8333-333333333333'),'uploader reference cannot be restored')
# This is the only deletion in the suite: an explicitly named synthetic fixture.
run('RESTRICT rehearsal preserves nonlegacy objects',suffix=verify+"DROP TABLE public.inventory_lines,public.inventory_uploads,public.products_master RESTRICT;\nDO $$ BEGIN IF (SELECT other_state FROM qa_before) IS DISTINCT FROM pg_temp.sec03_fingerprint() THEN RAISE EXCEPTION 'Unrelated objects changed'; END IF; END; $$;\n")
print(json.dumps({'scenarios_passed':8,'production_requests':0,'customer_records_exported':0,'fixture_counts':[1576,1,1309]}))
