const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const root=process.argv[2]||'.',html=fs.readFileSync(root+'/index.html','utf8');
const inline=[...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)].map(x=>x[1]);
const elements=new Map(),store=new Map();
function el(id=''){if(elements.has(id))return elements.get(id);const o={id,value:'',textContent:'',innerHTML:'',options:[],dataset:{},disabled:false,checked:false,style:{setProperty(){}},classList:{contains(){return true},add(){},remove(){},toggle(){}},setAttribute(){},getAttribute(){},addEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},append(){},setCustomValidity(){},getBoundingClientRect(){return{top:0,bottom:0}},offsetHeight:0};elements.set(id,o);return o;}
const context=vm.createContext({console,crypto:crypto.webcrypto,URL,TextDecoder,TextEncoder,structuredClone,AbortController,Date,Set,Map,Blob,document:{getElementById:el,querySelector:()=>el('query'),querySelectorAll:()=>[],createElement:()=>el('new'),body:el('body'),documentElement:el('html'),hidden:false,addEventListener(){}},navigator:{onLine:true},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}},matchMedia:()=>({matches:true}),setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,requestAnimationFrame(){},queueMicrotask,addEventListener(){},location:{},fetch:async()=>{throw Error('Unexpected network')}});context.window=context;
// Execute local scripts in document order, including the new shared risk modules.
for(const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)){
 const src=match[1].match(/src="([^"]+)"/);
 vm.runInContext(src?fs.readFileSync(root+'/'+src[1].split('?')[0],'utf8'):match[2],context);
}
const run=s=>vm.runInContext(s,context);let passed=0;
function test(name,fn){fn();passed++;console.log('PASS',name);}
const day=new Date().toISOString().slice(0,10);
function row(code,supplier,stock,profit='Super',price=20,review=false){return{product_code:code,product_name:code,supplier,stock_qty:stock,reorder_point:100,stock_ratio:stock,purchase_price:price,min_order_qty:Math.max(0,120-stock),max_order_qty:Math.max(0,200-stock),needs_review:review,review_reason:review?'Master purchase price is missing or zero':null,profitability_class:profit,purchase_unit:'Piece',factor:1,raw_unit:'Piece',raw_quantity:stock,total_value:stock*price,stock_origin:'reported',conversion_role:'purchase'};}
const rows=[row('a','A',20),row('b','B',30,'High'),row('c','A',150),row('d','C',200,'Low'),row('e','B',5,'Medium'),row('review','C',35,'Super',0,true),row('f','C',250,'High')];
const base={schema_version:5,seed_applied:true,rows,master:rows.map(r=>({...r,option_unit:null,order_multiple:1,reorder_point_unit:'Piece'})),aliases:[],master_revision:1,role:'admin',upload:{id:'11111111-1111-4111-8111-111111111111',snapshot_date:day,uploaded_at:new Date().toISOString(),status:'completed',is_complete:true,excludes_zero:true}};
const derive=d=>{context.fixture=d;return run('deriveWorkspace(fixture)')};let first;run('loadShortageStore()');
test('deterministic derivation without modifying current state',()=>{const before=run('JSON.stringify(state)');first=derive(base);const again=derive(base);assert.equal(JSON.stringify(first.tasks),JSON.stringify(again.tasks));assert.equal(first.model.score,again.model.score);assert.equal(run('JSON.stringify(state)'),before);});
test('supplier reassignment preserves product calculations',()=>{const changed=structuredClone(base);changed.master_revision=2;changed.rows[0].supplier='B';changed.master[0].supplier='B';const next=derive(changed),a=next.tasks.find(t=>t.target==='A'),b=next.tasks.find(t=>t.target==='B');assert(!a||!a.codes.includes('a'));assert(b.codes.includes('a'));for(const k of ['stock_qty','purchase_price','reorder_point','min_order_qty','max_order_qty'])assert.equal(next.dataset.rows[0][k],first.dataset.rows[0][k]);assert(!next.tasks.some(t=>t.status==='completed'));});
test('review repair propagates into recovery and supplier work',()=>{const next=structuredClone(base);next.master_revision=2;Object.assign(next.rows[5],{needs_review:false,review_reason:null,purchase_price:100});next.master[5].purchase_price=100;const d=derive(next);assert(!d.tasks.find(t=>t.focus==='data'));assert(d.tasks.find(t=>t.focus==='profit_recovery').codes.includes('review'));assert(d.tasks.find(t=>t.target==='C').codes.includes('review'));assert(first.tasks.find(t=>t.focus==='shortage_mid').codes.includes('review'));});
test('joint impact deduplicates overlapping product outcomes',()=>{context.first=first;run('Object.assign(state,first.dataset);state.shortageCycles=first.cycles');const a=run("combinedTaskImpact(first.model,[{focus:'suppliers',codes:['a','b']},{focus:'profit_recovery',codes:['a']}])"),b=run("combinedTaskImpact(first.model,[{focus:'suppliers',codes:['a','b']}])");assert.equal(a,b);});
test('top ten supplier order uses the same impact engine',()=>{const impacts=first.tasks.filter(t=>t.focus==='suppliers').map(t=>t.score_impact);assert(impacts.length<=10);assert.deepEqual([...impacts].sort((a,b)=>b-a),[...impacts]);});
test('approved score and financial formula contracts unchanged',()=>{for(const snippet of ["profit*.50+severity*.30+valueScore*.20","commercialExposure=shortageBreadth*.40+averageShortageImpact*.60","components.commercial*.70+components.aging*.15+components.suppliers*.10+components.data*.05","avg*Number(r.purchase_price)","shortage={Super:1.5,High:1.2,Medium:.8,Low:.6,Loss:.4}"])assert(html.includes(snippet),snippet);});
test('build 82 keeps canonical risk math and loads stage-specific supplier quest workspace',()=>{assert(html.includes('Content-Security-Policy'));assert(html.includes('overstock-risk-v69.js?v=71'));assert(html.includes('overstock-ui-v69.js?v=77'));assert(html.includes('overstock-risk-v69.css?v=77'));assert(html.includes('supplier-quest-model-v81.js?v=81'));assert(html.includes('supplier-task-v82.js?v=82'));assert(html.includes('supplier-task-v82.css?v=82'));assert(html.includes('<option value="gt200">Above 200%</option><option value="gt300">Above 300%</option>'));assert(html.includes("case'gt300':return v>300"));assert(html.includes('Stock Above 300%'));assert(html.includes('renderOverstockKpi(totalInventory)'));assert(!html.includes('overstockProfitRisk'));assert(!html.includes('adjustedOverstockPct'));assert(html.includes('Live Build 86'));assert(html.includes('supplier-toolbar-v85.js?v=85'));assert(html.includes('supplier-toolbar-v85.css?v=85'));assert(html.includes('tasks-focus-v86.js?v=86'));assert(html.includes('tasks-focus-v86.css?v=86'));assert(html.includes('data-tab="output-lists"'));assert(html.includes('data-panel="output-lists"'));assert(html.includes('supplier-layout-v83.js?v=83'));assert(html.includes('supplier-layout-v83.css?v=83'));});
test('unsafe old completion and client-authority sync are no longer used',()=>{assert(html.includes('workspace-v47.js'));assert(!html.includes("rpc('purchasing_tasks_sync_logic_v5',{payload})"));assert(!html.includes("data.tasks.filter(t=>t.status==='open'&&!taskStillOpen(t))"));assert(!fs.readFileSync(root+'/assets/js/workspace-v47.js','utf8').includes("rpc('purchasing_workspace_sync_v47'"));});
(async()=>{run("state.session={user:{id:'test'}};state.mode='live'");context.fixture=base;context.reads=0;context.commits=[];
run(`http=async(path,{body}={})=>{if(path.endsWith('purchasing_dashboard_v5')){reads++;return structuredClone(fixture)}if(path.endsWith('purchasing_workspace_state_v58')){const a=deriveWorkspace(fixture);return{cycles:a.cycles,score:Math.round(a.model.score),authority_version:'server_v58',source:{master_revision:fixture.master_revision,upload_id:fixture.upload.id}}}if(path.endsWith('purchasing_workspace_sync_v58'))return{tasks:body.payload.tasks.map(t=>({...t,status:'open'})),cycles:structuredClone(state.shortageCycles),authority:{score:body.payload.score,authority_version:'server_v58'},source:{master_revision:body.payload.master_revision,upload_id:body.payload.upload_id}};throw Error(path)};commitWorkspace=(r,d)=>{commits.push(r.dataset.revision);Object.assign(state,r.dataset)};`);
await run('Promise.all([loadLive(),loadLive(),loadLive()])');test('concurrent refresh is serialized; older response not displayed',()=>{assert.equal(context.reads,2);assert.deepEqual([...context.commits],[1]);});
context.stale=structuredClone(base);context.stale.master_revision=9;context.stale.upload={...context.stale.upload,id:'99999999-9999-4999-8999-999999999999',uploaded_at:new Date(Date.now()-72*3600000).toISOString(),snapshot_date:new Date(Date.now()-72*3600000).toISOString().slice(0,10)};context.staleSyncCalls=0;
run(`WORKSPACE_RUNTIME.serverShortageReady=false;state.shortageStoreLoaded=false;state.taskAssistant=null;http=async(path,{body}={})=>{if(path.endsWith('purchasing_dashboard_v5'))return structuredClone(stale);if(path.endsWith('purchasing_workspace_state_v58')){const a=deriveWorkspace(stale);return{cycles:a.cycles,score:Math.round(a.model.score),authority_version:'server_v58',source:{master_revision:stale.master_revision,upload_id:stale.upload.id}}}if(path.endsWith('purchasing_workspace_sync_v58')){staleSyncCalls++;throw Error('STALE_SYNC_MUST_NOT_RUN')}throw Error(path)};`);
await run('loadLive()');
test('stale inventory loads current master/revision for upload without task sync',()=>{assert.equal(context.staleSyncCalls,0);assert.equal(run('state.revision'),9);assert.equal(run('state.master.length'),context.stale.master.length);assert.equal(run('state.upload.id'),context.stale.upload.id);assert.equal(run('inventoryFreshness().fresh'),false);});
context.fixture=base;run('WORKSPACE_RUNTIME.serverShortageReady=false;state.shortageStoreLoaded=false');
context.failNext=true;run(`http=async(path,{body}={})=>{if(path.endsWith('purchasing_dashboard_v5')){reads++;return structuredClone(fixture)}if(path.endsWith('purchasing_workspace_state_v58')){const a=deriveWorkspace(fixture);return{cycles:a.cycles,score:Math.round(a.model.score),source:{master_revision:fixture.master_revision,upload_id:fixture.upload.id}}}if(path.endsWith('purchasing_workspace_sync_v58')){if(failNext){failNext=false;throw Error('SOURCE_REVISION_CHANGED')}return{tasks:body.payload.tasks.map(t=>({...t,status:'open'})),cycles:structuredClone(state.shortageCycles),authority:{score:body.payload.score,authority_version:'server_v58'},source:{master_revision:body.payload.master_revision,upload_id:body.payload.upload_id}}}throw Error(path)};`);
await run('loadLive()');test('revision conflict reruns the dependency chain',()=>assert.equal(context.failNext,false));console.log('TOTAL',passed,'tests passed');})().catch(e=>{console.error(e);process.exitCode=1});
