-- SEC-03 phase A: owner-only recovery snapshot. No production table deletion.
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '90s';
SET LOCAL search_path = pg_catalog;
CREATE FUNCTION pg_temp.sec03_fingerprint() RETURNS jsonb LANGUAGE plpgsql AS $f$
DECLARE r record; n bigint; h text; result jsonb := '{}'::jsonb; funcs text;
BEGIN
 FOR r IN SELECT c.oid,c.relname,ns.nspname,c.relacl,c.relrowsecurity,c.relforcerowsecurity FROM pg_class c JOIN pg_namespace ns ON ns.oid=c.relnamespace WHERE ns.nspname IN ('public','purchasing_private') AND c.relkind IN ('r','p') AND NOT (ns.nspname='public' AND c.relname IN ('products_master','inventory_uploads','inventory_lines')) AND NOT (ns.nspname='purchasing_private' AND c.relname='retired_legacy_snapshot_v1') ORDER BY ns.nspname,c.relname LOOP
  EXECUTE format('SELECT count(*),md5(coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),''[]''::jsonb)::text) FROM %I.%I t',r.nspname,r.relname) INTO n,h;
  result := result || jsonb_build_object(r.nspname||'.'||r.relname,jsonb_build_object('rows',n,'data',h,'acl',r.relacl,'rls',r.relrowsecurity,'force_rls',r.relforcerowsecurity,'structure',(SELECT md5(jsonb_build_object('columns',(SELECT jsonb_agg(jsonb_build_array(a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull,a.attidentity,pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=r.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints',(SELECT jsonb_agg(pg_get_constraintdef(c.oid) ORDER BY c.conname) FROM pg_constraint c WHERE c.conrelid=r.oid),'indexes',(SELECT jsonb_agg(indexdef ORDER BY indexname) FROM pg_indexes WHERE schemaname=r.nspname AND tablename=r.relname),'policies',(SELECT jsonb_agg(to_jsonb(p) ORDER BY policyname) FROM pg_policies p WHERE schemaname=r.nspname AND tablename=r.relname))::text))));
 END LOOP;
 SELECT md5(coalesce(string_agg(p.oid::regprocedure::text||pg_get_functiondef(p.oid)||coalesce(p.proacl::text,''),E'\n' ORDER BY p.oid::regprocedure::text),'')) INTO funcs FROM pg_proc p JOIN pg_namespace ns ON ns.oid=p.pronamespace WHERE ns.nspname IN ('public','purchasing_private') AND p.prokind IN ('f','p');
 RETURN jsonb_build_object('tables',result,'routines_and_acls',funcs);
END $f$;
CREATE FUNCTION pg_temp.sec03_capture() RETURNS jsonb LANGUAGE plpgsql AS $f$
DECLARE name text; rel oid; cols text; data jsonb; bundle jsonb:='{}'; item jsonb; seqname text; seqstate jsonb;
BEGIN
 FOREACH name IN ARRAY ARRAY['products_master','inventory_uploads','inventory_lines'] LOOP
  rel:=to_regclass('public.'||name);
  IF rel IS NULL THEN RAISE EXCEPTION 'SEC03 missing source table: %',name; END IF;
  IF EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=rel AND attnum>0 AND NOT attisdropped AND (attgenerated<>'' OR attidentity='a')) THEN RAISE EXCEPTION 'SEC03 unsupported generated column'; END IF;
  SELECT string_agg(format('%I %s%s%s',a.attname,format_type(a.atttypid,a.atttypmod),CASE WHEN a.attidentity='d' THEN ' GENERATED BY DEFAULT AS IDENTITY' WHEN d.adbin IS NOT NULL THEN ' DEFAULT '||pg_get_expr(d.adbin,d.adrelid) ELSE '' END,CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END),', ' ORDER BY a.attnum) INTO cols FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=rel AND a.attnum>0 AND NOT a.attisdropped;
  EXECUTE format('SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),''[]''::jsonb) FROM public.%I t',name) INTO data;
  seqname:=NULL;
  IF EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=rel AND attname='id' AND attidentity<>'') THEN seqname:=pg_get_serial_sequence('public.'||name,'id'); END IF;
  seqstate:=NULL;
  IF seqname IS NOT NULL THEN
   EXECUTE format('SELECT jsonb_build_object(''last_value'',last_value,''is_called'',is_called) FROM %s',seqname) INTO seqstate;
   seqstate:=seqstate||jsonb_build_object('name',seqname,'column','id','settings',(SELECT to_jsonb(s) FROM pg_sequences s WHERE schemaname||'.'||sequencename=seqname));
  END IF;
  item:=jsonb_build_object('create_sql',format('CREATE TABLE public.%I (%s)',name,cols),'data',data,'row_count',jsonb_array_length(data),'data_md5',md5(data::text),'sequence',seqstate,'constraints',coalesce((SELECT jsonb_agg(jsonb_build_object('name',conname,'definition',pg_get_constraintdef(oid)) ORDER BY conname) FROM pg_constraint WHERE conrelid=rel),'[]'),'indexes',coalesce((SELECT jsonb_agg(pg_get_indexdef(i.indexrelid) ORDER BY i.indexrelid) FROM pg_index i WHERE i.indrelid=rel AND NOT EXISTS(SELECT 1 FROM pg_constraint c WHERE c.conindid=i.indexrelid)),'[]'),'triggers',coalesce((SELECT jsonb_agg(pg_get_triggerdef(t.oid) ORDER BY t.tgname) FROM pg_trigger t WHERE t.tgrelid=rel AND NOT t.tgisinternal),'[]'),'policies',coalesce((SELECT jsonb_agg(to_jsonb(p) ORDER BY p.policyname) FROM pg_policies p WHERE p.schemaname='public' AND p.tablename=name),'[]'),'table_metadata',(SELECT jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl,'rls',relrowsecurity,'force_rls',relforcerowsecurity,'comment',obj_description(oid,'pg_class')) FROM pg_class WHERE oid=rel),'column_comments',(SELECT jsonb_object_agg(attname,col_description(attrelid,attnum)) FROM pg_attribute WHERE attrelid=rel AND attnum>0 AND NOT attisdropped));
  bundle:=bundle||jsonb_build_object(name,item);
 END LOOP;
 RETURN jsonb_build_object('format','sec03_logical_snapshot_v1','tables',bundle,'supporting_function',pg_get_functiondef(to_regprocedure('public.set_updated_at()')));
END $f$;
CREATE TABLE purchasing_private.retired_legacy_snapshot_v1(snapshot_key text PRIMARY KEY,captured_at timestamptz NOT NULL DEFAULT now(),payload jsonb NOT NULL,payload_md5 text NOT NULL,verification jsonb NOT NULL);
ALTER TABLE purchasing_private.retired_legacy_snapshot_v1 ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE purchasing_private.retired_legacy_snapshot_v1 FROM PUBLIC,anon,authenticated,service_role;
COMMENT ON TABLE purchasing_private.retired_legacy_snapshot_v1 IS 'SEC03 one-time isolated logical recovery snapshot in this database. Owner-only, not an operational source or synchronized backup. Restore only through reviewed SQL, with RLS enabled and no broad client policies.';
DO $backup$
DECLARE bundle jsonb; before_state jsonb;
BEGIN
 LOCK TABLE public.products_master,public.inventory_uploads,public.inventory_lines IN SHARE MODE;
 before_state:=pg_temp.sec03_fingerprint();
 bundle:=pg_temp.sec03_capture();
 INSERT INTO purchasing_private.retired_legacy_snapshot_v1(snapshot_key,payload,payload_md5,verification) VALUES('sec03_legacy_retirement',bundle,md5(bundle::text),jsonb_build_object('before',before_state,'status','backup_only_pending_restore_test'));
 IF before_state IS DISTINCT FROM pg_temp.sec03_fingerprint() THEN RAISE EXCEPTION 'SEC03 unrelated state changed'; END IF;
END $backup$;
DROP FUNCTION pg_temp.sec03_capture();
DROP FUNCTION pg_temp.sec03_fingerprint();