-- SEC03 phase B. User-authorized retirement of exactly three legacy tables.
-- Restore gate runs first using the protected snapshot; failure aborts everything.
-- No project, V5 table, shared function, current history or Auth account deletion.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='90s';
SET LOCAL search_path=pg_catalog;
CREATE FUNCTION pg_temp.sec03_fingerprint() RETURNS jsonb LANGUAGE plpgsql AS $f$
DECLARE r record; n bigint; h text; result jsonb := '{}'::jsonb; funcs text;
BEGIN
 FOR r IN SELECT c.oid,c.relname,ns.nspname,c.relacl,c.relrowsecurity,c.relforcerowsecurity FROM pg_class c JOIN pg_namespace ns ON ns.oid=c.relnamespace WHERE ns.nspname IN ('public','purchasing_private') AND c.relkind IN ('r','p') AND NOT (ns.nspname='public' AND c.relname IN ('products_master','inventory_uploads','inventory_lines')) AND NOT (ns.nspname='purchasing_private' AND c.relname='retired_legacy_snapshot_v1') ORDER BY ns.nspname,c.relname LOOP
  EXECUTE format('SELECT count(*),md5(coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),''[]''::jsonb)::text) FROM %I.%I t',r.nspname,r.relname) INTO n,h;
  result := result || jsonb_build_object(r.nspname||'.'||r.relname,jsonb_build_object('rows',n,'data',h,'acl',r.relacl,'rls',r.relrowsecurity,'force_rls',r.relforcerowsecurity,'structure',(SELECT md5(jsonb_build_object('columns',(SELECT jsonb_agg(jsonb_build_array(a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull,a.attidentity,pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=r.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints',(SELECT jsonb_agg(pg_get_constraintdef(c.oid) ORDER BY c.conname) FROM pg_constraint c WHERE c.conrelid=r.oid),'indexes',(SELECT jsonb_agg(indexdef ORDER BY indexname) FROM pg_indexes WHERE schemaname=r.nspname AND tablename=r.relname),'policies',(SELECT jsonb_agg(to_jsonb(p) ORDER BY policyname) FROM pg_policies p WHERE schemaname=r.nspname AND tablename=r.relname))::text))));
 END LOOP;
 SELECT md5(coalesce(string_agg(p.oid::regprocedure::text||pg_get_functiondef(p.oid)||coalesce(p.proacl::text,''),E'\n' ORDER BY p.oid::regprocedure::text),'')) INTO funcs FROM pg_proc p JOIN pg_namespace ns ON ns.oid=p.pronamespace WHERE ns.nspname IN ('public','purchasing_private') AND p.prokind IN ('f','p');
 RETURN jsonb_build_object('tables',result,'routines_and_acls',funcs);
END $f$;
CREATE FUNCTION pg_temp.sec03_capture() RETURNS jsonb LANGUAGE plpgsql AS $f$
DECLARE name text; rel oid; cols text; data jsonb; bundle jsonb:='{}'; item jsonb; seqname text; seqstate jsonb;
BEGIN
 FOREACH name IN ARRAY ARRAY['products_master','inventory_uploads','inventory_lines'] LOOP
  rel:=to_regclass('public.'||name);
  IF rel IS NULL THEN RAISE EXCEPTION 'SEC03 missing source table: %',name; END IF;
  IF EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=rel AND attnum>0 AND NOT attisdropped AND (attgenerated<>'' OR attidentity='a')) THEN RAISE EXCEPTION 'SEC03 unsupported generated column'; END IF;
  SELECT string_agg(format('%I %s%s%s',a.attname,format_type(a.atttypid,a.atttypmod),CASE WHEN a.attidentity='d' THEN ' GENERATED BY DEFAULT AS IDENTITY' WHEN d.adbin IS NOT NULL THEN ' DEFAULT '||pg_get_expr(d.adbin,d.adrelid) ELSE '' END,CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END),', ' ORDER BY a.attnum) INTO cols FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=rel AND a.attnum>0 AND NOT a.attisdropped;
  EXECUTE format('SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),''[]''::jsonb) FROM public.%I t',name) INTO data;
  seqname:=NULL;
  IF EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=rel AND attname='id' AND attidentity<>'') THEN seqname:=pg_get_serial_sequence('public.'||name,'id'); END IF;
  seqstate:=NULL;
  IF seqname IS NOT NULL THEN
   EXECUTE format('SELECT jsonb_build_object(''last_value'',last_value,''is_called'',is_called) FROM %s',seqname) INTO seqstate;
   seqstate:=seqstate||jsonb_build_object('name',seqname,'column','id','settings',(SELECT to_jsonb(s) FROM pg_sequences s WHERE schemaname||'.'||sequencename=seqname));
  END IF;
  item:=jsonb_build_object('create_sql',format('CREATE TABLE public.%I (%s)',name,cols),'data',data,'row_count',jsonb_array_length(data),'data_md5',md5(data::text),'sequence',seqstate,'constraints',coalesce((SELECT jsonb_agg(jsonb_build_object('name',conname,'definition',pg_get_constraintdef(oid)) ORDER BY conname) FROM pg_constraint WHERE conrelid=rel),'[]'),'indexes',coalesce((SELECT jsonb_agg(pg_get_indexdef(i.indexrelid) ORDER BY i.indexrelid) FROM pg_index i WHERE i.indrelid=rel AND NOT EXISTS(SELECT 1 FROM pg_constraint c WHERE c.conindid=i.indexrelid)),'[]'),'triggers',coalesce((SELECT jsonb_agg(pg_get_triggerdef(t.oid) ORDER BY t.tgname) FROM pg_trigger t WHERE t.tgrelid=rel AND NOT t.tgisinternal),'[]'),'policies',coalesce((SELECT jsonb_agg(to_jsonb(p) ORDER BY p.policyname) FROM pg_policies p WHERE p.schemaname='public' AND p.tablename=name),'[]'),'table_metadata',(SELECT jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl,'rls',relrowsecurity,'force_rls',relforcerowsecurity,'comment',obj_description(oid,'pg_class')) FROM pg_class WHERE oid=rel),'column_comments',(SELECT jsonb_object_agg(attname,col_description(attrelid,attnum)) FROM pg_attribute WHERE attrelid=rel AND attnum>0 AND NOT attisdropped));
  bundle:=bundle||jsonb_build_object(name,item);
 END LOOP;
 RETURN jsonb_build_object('format','sec03_logical_snapshot_v1','tables',bundle,'supporting_function',pg_get_functiondef(to_regprocedure('public.set_updated_at()')));
END $f$;
LOCK TABLE public.products_master,public.inventory_uploads,public.inventory_lines IN ACCESS EXCLUSIVE MODE;
CREATE TEMP TABLE sec03_guard(before_state jsonb,snapshot_md5 text) ON COMMIT DROP;
DO $gate$
DECLARE b jsonb; h text;
BEGIN
 SELECT payload,payload_md5 INTO b,h FROM purchasing_private.retired_legacy_snapshot_v1 WHERE snapshot_key='sec03_legacy_retirement' FOR UPDATE;
 IF b IS NULL OR md5(b::text) IS DISTINCT FROM h OR b IS DISTINCT FROM pg_temp.sec03_capture()
 THEN RAISE EXCEPTION 'SEC03: snapshot/source drift; deletion refused'; END IF;
 IF EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('public','purchasing_private') AND p.prokind IN ('f','p') AND p.prosrc ~ '\m(products_master|inventory_uploads|inventory_lines)\M')
 THEN RAISE EXCEPTION 'SEC03: application routine references legacy source'; END IF;
 IF EXISTS(SELECT 1 FROM pg_publication_tables WHERE schemaname='public' AND tablename IN ('products_master','inventory_uploads','inventory_lines'))
 THEN RAISE EXCEPTION 'SEC03: legacy publication requires separate review'; END IF;
 INSERT INTO pg_temp.sec03_guard VALUES(pg_temp.sec03_fingerprint(),h);
END;
$gate$;
-- SEC03: NON-DESTRUCTIVE full logical restore rehearsal.
-- Writes only session-local temporary copies. Never drops a legacy/V5 table.
-- Do not use as a restore into production: old broad grants are never replayed.
SET LOCAL search_path = pg_catalog;
SET LOCAL statement_timeout = '60s';
CREATE TEMP TABLE sec03_restore_result(result jsonb) ON COMMIT DROP;
DO $restore$
DECLARE
 b jsonb; expected_hash text; name text; item jsonb; obj jsonb; ddl text;
 destination text; source_name text; n bigint; restored jsonb; result jsonb := '{}';
 seq text; s jsonb; seq_value bigint; seq_called boolean; seen integer := 0;
BEGIN
 SELECT payload,payload_md5 INTO b,expected_hash
 FROM purchasing_private.retired_legacy_snapshot_v1
 WHERE snapshot_key='sec03_legacy_retirement';
 IF b IS NULL OR md5(b::text) IS DISTINCT FROM expected_hash
    OR b->>'format' IS DISTINCT FROM 'sec03_logical_snapshot_v1'
    OR (SELECT array_agg(key ORDER BY key) FROM jsonb_each(b->'tables'))
       IS DISTINCT FROM ARRAY['inventory_lines','inventory_uploads','products_master']
 THEN RAISE EXCEPTION 'SEC03: missing, damaged or unsupported recovery snapshot'; END IF;
 IF b->>'supporting_function' IS DISTINCT FROM pg_get_functiondef('public.set_updated_at()'::regprocedure)
 THEN RAISE EXCEPTION 'SEC03: shared trigger source changed; review required'; END IF;

 CREATE TEMP TABLE sec03_restore_auth_ids(id uuid PRIMARY KEY) ON COMMIT DROP;
 REVOKE ALL ON TABLE pg_temp.sec03_restore_auth_ids FROM PUBLIC,anon,authenticated,service_role;
 INSERT INTO pg_temp.sec03_restore_auth_ids
 SELECT DISTINCT a.id FROM auth.users a
 JOIN jsonb_array_elements(b->'tables'->'inventory_uploads'->'data') u ON a.id::text=u->>'uploaded_by';
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(b->'tables'->'inventory_uploads'->'data') u
   WHERE u->>'uploaded_by' IS NOT NULL AND NOT EXISTS(
     SELECT 1 FROM pg_temp.sec03_restore_auth_ids a WHERE a.id::text=u->>'uploaded_by'))
 THEN RAISE EXCEPTION 'SEC03: snapshot uploader reference cannot be restored'; END IF;

 FOREACH name IN ARRAY ARRAY['products_master','inventory_uploads','inventory_lines'] LOOP
  item:=b->'tables'->name;
  destination:=format('pg_temp.%I','sec03_restore_'||name);
  source_name:='public.'||name;
  ddl:=item->>'create_sql';
  IF left(ddl,length('CREATE TABLE '||source_name||' (')) <> 'CREATE TABLE '||source_name||' ('
  THEN RAISE EXCEPTION 'SEC03: unexpected recovery DDL'; END IF;
  ddl:='CREATE TEMP TABLE '||quote_ident('sec03_restore_'||name)||substr(ddl,length('CREATE TABLE '||source_name)+1)||' ON COMMIT DROP';
  EXECUTE ddl;
  EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY',destination);
  EXECUTE format('REVOKE ALL ON TABLE %s FROM PUBLIC,anon,authenticated,service_role',destination);
  FOR obj IN SELECT value FROM jsonb_array_elements(item->'constraints') LOOP
   ddl:=obj->>'definition';
   ddl:=replace(ddl,'REFERENCES public.inventory_uploads(','REFERENCES pg_temp.sec03_restore_inventory_uploads(');
   ddl:=replace(ddl,'REFERENCES auth.users(','REFERENCES pg_temp.sec03_restore_auth_ids(');
   EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I %s',destination,obj->>'name',ddl);
  END LOOP;
  EXECUTE format('INSERT INTO %s SELECT * FROM jsonb_populate_recordset(NULL::%s,$1)',destination,destination) USING item->'data';
  EXECUTE format('SELECT count(*),coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),''[]''::jsonb) FROM %s t',destination) INTO n,restored;
  IF n IS DISTINCT FROM (item->>'row_count')::bigint OR restored IS DISTINCT FROM item->'data'
     OR md5(restored::text) IS DISTINCT FROM item->>'data_md5'
  THEN RAISE EXCEPTION 'SEC03: restore contents differ for %',name; END IF;
  FOR ddl IN SELECT jsonb_array_elements_text(item->'indexes') LOOP
   EXECUTE replace(ddl,' ON '||source_name||' ',' ON '||destination||' ');
  END LOOP;
  FOR ddl IN SELECT jsonb_array_elements_text(item->'triggers') LOOP
   EXECUTE replace(ddl,' ON '||source_name||' ',' ON '||destination||' ');
  END LOOP;
  IF item->'table_metadata'->>'comment' IS NOT NULL THEN
   EXECUTE format('COMMENT ON TABLE %s IS %L',destination,item->'table_metadata'->>'comment');
  END IF;
  FOR obj IN SELECT jsonb_build_object('column',key,'comment',value) FROM jsonb_each(item->'column_comments') LOOP
   IF jsonb_typeof(obj->'comment')='string' THEN
    EXECUTE format('COMMENT ON COLUMN %s.%I IS %L',destination,obj->>'column',obj->>'comment');
   END IF;
  END LOOP;
  IF jsonb_typeof(item->'sequence')='object' THEN
   s:=item->'sequence';seq:=pg_get_serial_sequence(destination,s->>'column');
   IF seq IS NULL OR (SELECT relnamespace FROM pg_class WHERE oid=seq::regclass)<>pg_my_temp_schema()
   THEN RAISE EXCEPTION 'SEC03: restore sequence is not temporary'; END IF;
   EXECUTE format('ALTER SEQUENCE %s INCREMENT BY %s MINVALUE %s MAXVALUE %s START WITH %s CACHE %s %s',
    seq,(s->'settings'->>'increment_by')::bigint,(s->'settings'->>'min_value')::bigint,
    (s->'settings'->>'max_value')::bigint,(s->'settings'->>'start_value')::bigint,
    (s->'settings'->>'cache_size')::bigint,CASE WHEN (s->'settings'->>'cycle')::boolean THEN 'CYCLE' ELSE 'NO CYCLE' END);
   PERFORM setval(seq::regclass,(s->>'last_value')::bigint,(s->>'is_called')::boolean);
   EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM PUBLIC,anon,authenticated,service_role',seq);
   EXECUTE format('SELECT last_value,is_called FROM %s',seq) INTO seq_value,seq_called;
   IF seq_value IS DISTINCT FROM (s->>'last_value')::bigint OR seq_called IS DISTINCT FROM (s->>'is_called')::boolean
   THEN RAISE EXCEPTION 'SEC03: sequence state mismatch'; END IF;
  END IF;
  IF EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid=destination::regclass AND NOT convalidated)
     OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid=destination::regclass)
     OR has_table_privilege('anon',destination,'SELECT') OR has_table_privilege('authenticated',destination,'SELECT')
  THEN RAISE EXCEPTION 'SEC03: restore constraints/access validation failed'; END IF;
  result:=result||jsonb_build_object(name,jsonb_build_object('restored_rows',n,'data_md5',md5(restored::text),
   'constraints_validated',true,'broad_policies_replayed',false,'sequence_checked',jsonb_typeof(item->'sequence')='object'));
  seen:=seen+1;
 END LOOP;
 IF seen<>3 THEN RAISE EXCEPTION 'SEC03: incomplete restore'; END IF;
 INSERT INTO pg_temp.sec03_restore_result VALUES(jsonb_build_object('status','restored_to_session_temporary_tables',
   'snapshot_md5',expected_hash,'tables',result,'business_table_writes',0));
END;
$restore$;
SELECT result FROM pg_temp.sec03_restore_result;

DO $verify$
BEGIN
 IF (SELECT before_state FROM pg_temp.sec03_guard) IS DISTINCT FROM pg_temp.sec03_fingerprint()
 THEN RAISE EXCEPTION 'SEC03: unrelated source changed during rehearsal'; END IF;
 IF (SELECT result->>'snapshot_md5' FROM pg_temp.sec03_restore_result) IS DISTINCT FROM (SELECT snapshot_md5 FROM pg_temp.sec03_guard)
 THEN RAISE EXCEPTION 'SEC03: restore report mismatch'; END IF;
END;
$verify$;
-- Deliberately explicit RESTRICT: any unexpected external dependency aborts.
DROP TABLE public.inventory_lines,public.inventory_uploads,public.products_master RESTRICT;
DO $finish$
DECLARE proof jsonb;
BEGIN
 IF (SELECT before_state FROM pg_temp.sec03_guard) IS DISTINCT FROM pg_temp.sec03_fingerprint()
 THEN RAISE EXCEPTION 'SEC03: nonlegacy data/structure/routine drift; deletion rolled back'; END IF;
 SELECT result INTO proof FROM pg_temp.sec03_restore_result;
 UPDATE purchasing_private.retired_legacy_snapshot_v1
 SET verification=verification||jsonb_build_object('status','retired_after_verified_restore','retirement',jsonb_build_object('at',clock_timestamp(),'restore',proof,'nonlegacy_fingerprint',pg_temp.sec03_fingerprint()))
 WHERE snapshot_key='sec03_legacy_retirement' AND payload_md5=(SELECT snapshot_md5 FROM pg_temp.sec03_guard) AND md5(payload::text)=payload_md5;
 IF NOT FOUND THEN RAISE EXCEPTION 'SEC03: recovery record changed'; END IF;
END;
$finish$;
DROP FUNCTION pg_temp.sec03_capture();
DROP FUNCTION pg_temp.sec03_fingerprint();
